const CONSTANTS = {
    MIN_POSSIBLE_WAGE: 0,
    MAX_POSSIBLE_WAGE: 600,
    MIN_POSSIBLE_AGE: 15,
    MAX_POSSIBLE_AGE: 34,
    AGE_INTERVAL: 5,
    NUM_INTERVALS: 15,
    DELAY: 3000
};

export default CONSTANTS;